//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_items_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermissionItem
    {
        public int id { get; set; }
        public int SupplyPermissionID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ProducationDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SupplyPermission SupplyPermission { get; set; }
    }
}
